# Generated by Django 3.2.4 on 2021-07-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
