# Generated by Django 3.2.4 on 2021-07-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_why_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_us',
            name='card_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
