# Generated by Django 3.2.4 on 2021-07-11 23:29

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_event_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Gallery.get_file_name)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(max_length=700, unique=True),
        ),
    ]
