# Generated by Django 3.2.4 on 2021-07-11 23:48

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_gallery_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('photo', models.ImageField(upload_to=main_page.models.Chefs.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
