# Generated by Django 3.2.4 on 2021-07-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_chefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='facebook_url',
            field=models.URLField(default='WWW'),
        ),
        migrations.AddField(
            model_name='chefs',
            name='twitter_url',
            field=models.URLField(default='fff'),
        ),
    ]
