# Generated by Django 3.2.4 on 2021-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20210713_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_subject', models.CharField(max_length=40)),
                ('user_message', models.CharField(max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
