# Generated by Django 3.2.4 on 2021-07-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_rename_media_url_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
